name: main workflow

on: 
    push:
        branches:
            - main
            - develop
            - do-do
        paths-ignore:
          -'CHANGELOG.md'

jobs: 
    firstJob:
        strategy:
            matrix:
                os: [ ubuntu-latest ] #windows-latestt
                java-version: [16, 18]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: actions/setup-java@v1
              with:
                java-version:  ${{ matrix.java-version }}
            - name: Setup kotlin
              uses: fwilhe2/setup-kotlin@main
              with:
                version: 1.7.10
            - name: gradle build
              run: ./gradlew build
    release:
      if: github.event_name == 'push'
      needs: firstJob
      permissions:
        contents: write
      runs-on: ubuntu-latest
      concurrency:
        group: release
        cancel-in-progress: false
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Release
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          run: |
            npm install
            npx semantic-release
          id: ver
      outputs:
        newVersion: ${{ steps.ver.outputs.nextVer }}

    swaggerhub-publish:
      needs: release
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - uses: ./.github/workflows/swaggerhub-publish
          with:
            token: ${{ secrets.SWAGGERHUB_TOKEN }}
            version: test-${{ needs.release.outputs.newVersion }}
