name: main workflow

on: 
    push:
        branches:
            - main
            - develop
            - do-do
        paths-ignore:
          -'CHANGELOG.md'

jobs: 
    firstJob:
        strategy:
            matrix:
                os: [ ubuntu-latest ] #windows-latestt
        runs-on: ${{ matrix.os }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - uses: actions/setup-java@v1
              with:
                java-version: "16"
            - name: Setup kotlin
              uses: fwilhe2/setup-kotlin@main
              with:
                version: 1.7.10
            - name: gradle build
              run: ./gradlew build
    release:
      if: github.event_name == 'push'
      needs: firstJob
      permissions:
        contents: write
      runs-on: ubuntu-latest
      concurrency:
        group: release
        cancel-in-progress: false
      steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Release
          env:
            GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          run: |
            npm install
            npx semantic-release
          id: ver
      outputs:
        newVersion: ${{ steps.ver.outputs.nextVer }}
    swagger:
      needs: release
      runs-on: ubuntu-latest
      env:
        FILE: ./swagger.yaml
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v3
        - name: Check version
          run: echo ${{ needs.release.outputs.newVersion }}
        - name: Validate OpenAPI definition
          uses: char0n/swagger-editor-validate@v1
          with:
            definition-file: ${{ env.FILE }}
        - name: Install SwaggerHub CLI
          run: npm install -g swaggerhub-cli     
        - name: Upload Swagger File
          run: |
            export SWAGGERHUB_API_KEY=${{ secrets.SWAGGERHUB_TOKEN }}
            swaggerhub api:update DenGuzawr22/DSDMS/${{ needs.release.outputs.newVersion }} --file ${{ env.FILE }}