name: main workflow

on: 
    push:
        branches:
            - main
            - develop

jobs: 
    firstJob:
        strategy:
            matrix:
                os: [ ubuntu-latest ] #windows-latest
        runs-on: ${{ matrix.os }} # Operating system selection
        steps:
            - run: echo "Hello World"
            - name: Checkout
              uses: actions/checkout@v2
            - uses: actions/setup-java@v1 # Add this step (if possible)
              with:
                java-version: "16"
            - name: Setup kotlin
              uses: fwilhe2/setup-kotlin@main
              with:
                version: 1.7.10
            - name: gradle build
              run: ./gradlew build
#            - name: docker compose
#              uses: isbang/compose-action@v1.4.1
#              with:
#                down-flags: "--volumes"
#                services: dossier_service
#            - name: run tests
#              run: ./gradlew SystemTester:run