name: swaggerhub publish

on:
  push:
    paths:
      - './docs/src/*'
      
jobs:
 swagger:
  runs-on: ubuntu-latest
  env:
    SRCFILE: ./docs/src/swagger.yaml
    FILE: ./build/openapi/openapi.yaml
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: reusePublish
      uses: ./.github/workflows/swagger-publish