name: swaggerhub publish

on:
  push:
    branches: 
      - main
#     paths:
#       - 'docs/src/*'
      
jobs:
 swagger:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - uses: ./.github/workflows/swaggerhub-publish
      with:
        token: ${{ secrets.SWAGGERHUB_TOKEN }}
        type: update
