name: swaggerhub publish

on:
  push:
    paths:
      - 'docs/src/*'
      
jobs:
 swagger:
  runs-on: ubuntu-latest
  steps:
    - uses: ./.github/workflows/swaggerhub-publish
      with:
        token: ${{ secrets.SWAGGERHUB_TOKEN }}