name: swaggerhub publish

on:
  push:
    paths:
      - 'swagger.yaml'
      
jobs:
 swagger:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Install SwaggerHub CLI
      run: npm install -g swaggerhub-cli     
    - name: Upload Swagger File
      run: |
        export SWAGGERHUB_API_KEY=${{ secrets.SWAGGERHUB_TOKEN }}
        swaggerhub api:update DenGuzawr22/DSDMS/0.0.1 --file ./swagger.yaml